server:
  port: 8021

file:
  dir: /Users/bangchan-u/Documents/GitHub/file-upload/src/main/resources/test/


logging:
  level:
    org:
      apache:
        coyote:
          http11: trace

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB